# Generated by Django 4.0.6 on 2023-05-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profileimg',
            field=models.ImageField(default='blank-profile-pic.png', upload_to='profile_images'),
        ),
    ]
